name: Daily Github Runner Cresta Dump
on: workflow_dispatch

# run at 12am everyday to get yesterdays value
  # schedule:
  #   - cron: "0 0 * * *"
jobs:
  daily-export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies and run
      env: 
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        CLICKBASE_USER: ${{ secrets.CLICKBASE_USER }}
        CLICKBASE_HOST: ${{ secrets.CLICKBASE_HOST }}
        CLICKBASE_PASSWORD: ${{ secrets.CLICKBASE_PASSWORD }}
        CLICKBASE_PORT: ${{ secrets.CLICKBASE_PORT }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py